/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule WelcomeSceneQuery.graphql
 * @generated SignedSource<<1cff7842abb8d555a0820156221bdbbc>>
 * @relayHash f2fcf63b278d6fc60f60e53873460270
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query WelcomeSceneQuery {
  viewer {
    login
    id
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "WelcomeSceneQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "User",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "login",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "WelcomeSceneQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "WelcomeSceneQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "User",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "login",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query WelcomeSceneQuery {\n  viewer {\n    login\n    id\n  }\n}\n"
};

module.exports = batch;
